repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3.10

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-docstrings',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-simplify',
            'flake8-return',
            'flake8-raise',
            'flake8-mutable',
            'flake8-future-import',
            'flake8-type-annotations',
            'flake8-unused-arguments',
            'flake8-variables-names',
            'flake8-import-order',
            'flake8-absolute-import',
            'flake8-broken-line',
            'flake8-commas',
            'flake8-debugger',
            'flake8-docstrings',
            'flake8-errmsg',
            'flake8-executable',
            'flake8-fixme',
            'flake8-future-import',
            'flake8-if-expressions',
            'flake8-import-order',
            'flake8-isort',
            'flake8-multiline-containers',
            'flake8-no-pep420',
            'flake8-pie',
            'flake8-print',
            'flake8-quotes',
            'flake8-return',
            'flake8-simplify',
            'flake8-super',
            'flake8-tidy-imports',
            'flake8-todo',
            'flake8-type-annotations',
            'flake8-unused-arguments',
            'flake8-use-fstring',
            'flake8-variables-names',
            'flake8-warnings',
        ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            'types-all',
            'types-requests',
            'types-setuptools',
        ]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]

-   repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
    -   id: yesqa

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ['bandit[toml]']

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.5.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
    -   id: mdformat
        additional_dependencies:
        - mdformat-gfm
        - mdformat-frontmatter
        - mdformat-footnote
        - mdformat-tables
        - mdformat-toc 